services:
    gs.e_transaction.signature.service:
        class: GS\ETransactionBundle\Services\SignatureService
        arguments:
            - '@request_stack'
            - '@event_dispatcher'
            - '%gse_transaction.public_key%'

    gs.e_transaction.button.service:
        class: GS\ETransactionBundle\Services\ButtonService
        arguments:
            - '@twig'

    gs.e_transaction.twig.extension:
        class: GS\ETransactionBundle\Twig\ButtonExtension
        arguments:
            - '@gs.e_transaction.button.service'
        tags:
            - { name: twig.extension }
